---

  - name: Add key
    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EA312927

  - name: Add repository
    apt_repository: repo="deb http://repo.mongodb.org/apt/ubuntu {{ ansible_lsb.codename }}/mongodb-org/3.2 multiverse"

  - name: Install mongodb
    apt: name={{item}}
    with_items:
      - mongodb-org
      - mongodb-org-server
      - mongodb-org-shell
      - mongodb-org-mongos
      - mongodb-org-tools
