---

- name: install git for RedHat family
  when: ansible_os_family == "RedHat"
  yum:
    name: git
    state: latest

- name: install git for Debian family
  when: ansible_os_family == "Debian"
  apt:
    name: git
    state: latest
